name: Cache Example

on:
  workflow_dispatch: # manually trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/mydeps   # replace with your dependencies path
          key: cache-0e1cb7f

      - name: prime-cache-0e1cb7f
        run: echo "Cache status: ${{ steps.cache.outputs.cache-hit }}"

